create table if not exists hitomi_gallery(
    id int not null primary key,
    other_id int not null,
    type text,
    title text,
    jpn_title text,
    tags text,
    artists text,
    groups text,
    parodies text,
    characters text,
    language text,
    language_localname text,
    language_url text,
    languages text,
    related text,
    date text,
    files text,
    file_count int,
    scene_indexes text,
    video text,
    videofilename text,
    galleryurl text,
    blocked text
)