CREATE table if not exists ex_gallery
(
    gid          int NOT NULL primary key,
    title        text,
    title_jpn    text,
    category     text,
    uploader     text,
    posted       int,
    thumb        text,
    filesize     int,
    filecount    int,
    expunged     int,
    torrentcount int,
    torrents     text,
    token        text,
    rating       Float,
    artist       text,
    group_name   text,
    parody       text,
    character    text,
    female       text,
    male         text,
    language     text,
    mixed        text,
    other        text,
    cosplayer    text,
    rest         text,
    parent_gid   int,
    parent_key   text,
    first_gid    int,
    first_key    text,
    disowned     int,
    removed      int,
    dumped       int
)